# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp
    pod 'SnapKit', '~> 5.0.0'
      pod 'Kingfisher', '~> 5.11'
      pod 'Alamofire', '~> 5.0.0-rc.3'
    pod 'MarqueeLabel'

 
  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
